use bitflags::bitflags;


bitflags! {
    #[allow(non_camel_case_types)]
    pub struct DOTA_ABILITY_BEHAVIOR: u32 {
        const DOTA_ABILITY_BEHAVIOR_NONE = 0;
        const DOTA_ABILITY_BEHAVIOR_HIDDEN = 1;
        const DOTA_ABILITY_BEHAVIOR_PASSIVE = 2;
        const DOTA_ABILITY_BEHAVIOR_NO_TARGET = 4;
        const DOTA_ABILITY_BEHAVIOR_UNIT_TARGET = 8;
        const DOTA_ABILITY_BEHAVIOR_POINT = 16;
        const DOTA_ABILITY_BEHAVIOR_AOE = 32;
        const DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE = 64;
        const DOTA_ABILITY_BEHAVIOR_CHANNELLED = 128;
        const DOTA_ABILITY_BEHAVIOR_ITEM = 256;
        const DOTA_ABILITY_BEHAVIOR_TOGGLE = 512;
        const DOTA_ABILITY_BEHAVIOR_DIRECTIONAL = 1024;
        const DOTA_ABILITY_BEHAVIOR_IMMEDIATE = 2048;
        const DOTA_ABILITY_BEHAVIOR_AUTOCAST = 4096;
        const DOTA_ABILITY_BEHAVIOR_OPTIONAL_UNIT_TARGET = 8192;
        const DOTA_ABILITY_BEHAVIOR_OPTIONAL_POINT = 16384;
        const DOTA_ABILITY_BEHAVIOR_OPTIONAL_NO_TARGET = 32768;
        const DOTA_ABILITY_BEHAVIOR_AURA = 65536;
        const DOTA_ABILITY_BEHAVIOR_ATTACK = 131072;
        const DOTA_ABILITY_BEHAVIOR_DONT_RESUME_MOVEMENT = 262144;
        const DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES = 524288;
        const DOTA_ABILITY_BEHAVIOR_UNRESTRICTED = 1048576;
        const DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE = 2097152;
        const DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL = 4194304;
        const DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_MOVEMENT = 8388608;
        const DOTA_ABILITY_BEHAVIOR_DONT_ALERT_TARGET = 16777216;
        const DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK = 33554432;
        const DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN = 67108864;
        const DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING = 134217728;
        const DOTA_ABILITY_BEHAVIOR_RUNE_TARGET = 268435456;
        const DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_CHANNEL = 536870912;
        const DOTA_ABILITY_BEHAVIOR_VECTOR_TARGETING = 1073741824;
    }
}