use bitflags::bitflags;

bitflags! {
    #[allow(non_camel_case_types)]
    pub struct DOTA_UNIT_TARGET_FLAGS: u32 {
        const DOTA_UNIT_TARGET_FLAG_NONE = 0;
        const DOTA_UNIT_TARGET_FLAG_RANGED_ONLY = 2;
        const DOTA_UNIT_TARGET_FLAG_MELEE_ONLY = 4;
        const DOTA_UNIT_TARGET_FLAG_DEAD = 8;
        const DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES = 16;
        const DOTA_UNIT_TARGET_FLAG_NOT_MAGIC_IMMUNE_ALLIES = 32;
        const DOTA_UNIT_TARGET_FLAG_INVULNERABLE = 64;
        const DOTA_UNIT_TARGET_FLAG_FOW_VISIBLE = 128;
        const DOTA_UNIT_TARGET_FLAG_NO_INVIS = 256;
        const DOTA_UNIT_TARGET_FLAG_CAN_BE_SEEN = 384;
        const DOTA_UNIT_TARGET_FLAG_NOT_ANCIENTS = 512;
        const DOTA_UNIT_TARGET_FLAG_PLAYER_CONTROLLED = 1024;
        const DOTA_UNIT_TARGET_FLAG_NOT_DOMINATED = 2048;
        const DOTA_UNIT_TARGET_FLAG_NOT_SUMMONED = 4096;
        const DOTA_UNIT_TARGET_FLAG_NOT_ILLUSIONS = 8192;
        const DOTA_UNIT_TARGET_FLAG_NOT_ATTACK_IMMUNE = 16384;
        const DOTA_UNIT_TARGET_FLAG_MANA_ONLY = 32768;
        const DOTA_UNIT_TARGET_FLAG_CHECK_DISABLE_HELP = 65536;
        const DOTA_UNIT_TARGET_FLAG_NOT_CREEP_HERO = 131072;
        const DOTA_UNIT_TARGET_FLAG_OUT_OF_WORLD = 262144;
        const DOTA_UNIT_TARGET_FLAG_NOT_NIGHTMARED = 524288;
        const DOTA_UNIT_TARGET_FLAG_PREFER_ENEMIES = 1048576;
        const DOTA_UNIT_TARGET_FLAG_RESPECT_OBSTRUCTIONS = 2097152;
    }
}

#[repr(i32)]
#[allow(non_camel_case_types)]
pub enum DOTA_UNIT_TARGET_TEAM {
    DOTA_UNIT_TARGET_TEAM_NONE = 0,
    DOTA_UNIT_TARGET_TEAM_FRIENDLY = 1,
    DOTA_UNIT_TARGET_TEAM_ENEMY = 2,
    DOTA_UNIT_TARGET_TEAM_BOTH = 3,
    DOTA_UNIT_TARGET_TEAM_CUSTOM = 4,
}

bitflags! {
    #[allow(non_camel_case_types)]
    pub struct DOTA_UNIT_TARGET_TYPE: u32 {
        const DOTA_UNIT_TARGET_NONE = 0;
        const DOTA_UNIT_TARGET_HERO = 1;
        const DOTA_UNIT_TARGET_CREEP = 2;
        const DOTA_UNIT_TARGET_BUILDING = 4;
        const DOTA_UNIT_TARGET_COURIER = 16;
        const DOTA_UNIT_TARGET_BASIC = 18;
        const DOTA_UNIT_TARGET_OTHER = 32;
        const DOTA_UNIT_TARGET_ALL = 55;
        const DOTA_UNIT_TARGET_TREE = 64;
        const DOTA_UNIT_TARGET_CUSTOM = 128;
        const DOTA_UNIT_TARGET_SELF = 256;
    }
}